# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='match.proto',
  package='robotgame',
  serialized_pb=_b('\n\x0bmatch.proto\x12\trobotgame\"\xf0\x02\n\x08Settings\x12\x11\n\tplayer_id\x18\x01 \x02(\x05\x12$\n\x03map\x18\x02 \x02(\x0b\x32\x17.robotgame.Settings.Map\x12\x12\n\x05turns\x18\x03 \x01(\x05:\x03\x31\x30\x30\x12\x16\n\x0bnum_players\x18\x04 \x01(\x05:\x01\x32\x12\x18\n\x0cspawn_period\x18\x05 \x01(\x05:\x02\x31\x30\x12\x17\n\x0cspawn_amount\x18\x06 \x01(\x05:\x01\x35\x12\x17\n\tsymmetric\x18\x07 \x01(\x08:\x04true\x1a\xb2\x01\n\x03Map\x12\x12\n\nboard_size\x18\x01 \x02(\x05\x12:\n\x0eobstacle_tiles\x18\x02 \x03(\x0b\x32\".robotgame.Settings.Map.Coordinate\x12\x37\n\x0bspawn_tiles\x18\x03 \x03(\x0b\x32\".robotgame.Settings.Map.Coordinate\x1a\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\"\xa1\x01\n\x05State\x12\x0c\n\x04turn\x18\x01 \x02(\x05\x12\"\n\x04\x62ots\x18\x02 \x03(\x0b\x32\x14.robotgame.State.Bot\x1a\x66\n\x03\x42ot\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x34\n\x08location\x18\x02 \x02(\x0b\x32\".robotgame.Settings.Map.Coordinate\x12\x11\n\tplayer_id\x18\x03 \x02(\x05\x12\n\n\x02hp\x18\x04 \x02(\x05\"\xed\x01\n\x07\x41\x63tions\x12\x0c\n\x04turn\x18\x01 \x02(\x05\x12*\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\x19.robotgame.Actions.Action\x1a\xa7\x01\n\x06\x41\x63tion\x12\x0e\n\x06\x62ot_id\x18\x01 \x02(\x05\x12\x34\n\x08location\x18\x02 \x02(\x0b\x32\".robotgame.Settings.Map.Coordinate\x12#\n\x04type\x18\x03 \x02(\x0e\x32\x15.robotgame.ActionType\x12\x32\n\x06target\x18\x04 \x01(\x0b\x32\".robotgame.Settings.Map.Coordinate*:\n\nActionType\x12\t\n\x05GUARD\x10\x00\x12\x08\n\x04MOVE\x10\x01\x12\n\n\x06\x41TTACK\x10\x02\x12\x0b\n\x07SUICIDE\x10\x03\x32M\n\x14TurnExecutionService\x12\x35\n\rTurnExecution\x12\x12.robotgame.Actions\x1a\x10.robotgame.StateB\x02H\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='robotgame.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GUARD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATTACK', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUICIDE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=801,
  serialized_end=859,
)
_sym_db.RegisterEnumDescriptor(_ACTIONTYPE)

ActionType = enum_type_wrapper.EnumTypeWrapper(_ACTIONTYPE)
GUARD = 0
MOVE = 1
ATTACK = 2
SUICIDE = 3



_SETTINGS_MAP_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='robotgame.Settings.Map.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robotgame.Settings.Map.Coordinate.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='robotgame.Settings.Map.Coordinate.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=395,
)

_SETTINGS_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='robotgame.Settings.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='board_size', full_name='robotgame.Settings.Map.board_size', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obstacle_tiles', full_name='robotgame.Settings.Map.obstacle_tiles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spawn_tiles', full_name='robotgame.Settings.Map.spawn_tiles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SETTINGS_MAP_COORDINATE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=395,
)

_SETTINGS = _descriptor.Descriptor(
  name='Settings',
  full_name='robotgame.Settings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='robotgame.Settings.player_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='map', full_name='robotgame.Settings.map', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turns', full_name='robotgame.Settings.turns', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_players', full_name='robotgame.Settings.num_players', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spawn_period', full_name='robotgame.Settings.spawn_period', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spawn_amount', full_name='robotgame.Settings.spawn_amount', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symmetric', full_name='robotgame.Settings.symmetric', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SETTINGS_MAP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=395,
)


_STATE_BOT = _descriptor.Descriptor(
  name='Bot',
  full_name='robotgame.State.Bot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='robotgame.State.Bot.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='robotgame.State.Bot.location', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='robotgame.State.Bot.player_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='robotgame.State.Bot.hp', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=559,
)

_STATE = _descriptor.Descriptor(
  name='State',
  full_name='robotgame.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='turn', full_name='robotgame.State.turn', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bots', full_name='robotgame.State.bots', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_STATE_BOT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=559,
)


_ACTIONS_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='robotgame.Actions.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bot_id', full_name='robotgame.Actions.Action.bot_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='robotgame.Actions.Action.location', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='robotgame.Actions.Action.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='robotgame.Actions.Action.target', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=632,
  serialized_end=799,
)

_ACTIONS = _descriptor.Descriptor(
  name='Actions',
  full_name='robotgame.Actions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='turn', full_name='robotgame.Actions.turn', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actions', full_name='robotgame.Actions.actions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACTIONS_ACTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=799,
)

_SETTINGS_MAP_COORDINATE.containing_type = _SETTINGS_MAP
_SETTINGS_MAP.fields_by_name['obstacle_tiles'].message_type = _SETTINGS_MAP_COORDINATE
_SETTINGS_MAP.fields_by_name['spawn_tiles'].message_type = _SETTINGS_MAP_COORDINATE
_SETTINGS_MAP.containing_type = _SETTINGS
_SETTINGS.fields_by_name['map'].message_type = _SETTINGS_MAP
_STATE_BOT.fields_by_name['location'].message_type = _SETTINGS_MAP_COORDINATE
_STATE_BOT.containing_type = _STATE
_STATE.fields_by_name['bots'].message_type = _STATE_BOT
_ACTIONS_ACTION.fields_by_name['location'].message_type = _SETTINGS_MAP_COORDINATE
_ACTIONS_ACTION.fields_by_name['type'].enum_type = _ACTIONTYPE
_ACTIONS_ACTION.fields_by_name['target'].message_type = _SETTINGS_MAP_COORDINATE
_ACTIONS_ACTION.containing_type = _ACTIONS
_ACTIONS.fields_by_name['actions'].message_type = _ACTIONS_ACTION
DESCRIPTOR.message_types_by_name['Settings'] = _SETTINGS
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Actions'] = _ACTIONS
DESCRIPTOR.enum_types_by_name['ActionType'] = _ACTIONTYPE

Settings = _reflection.GeneratedProtocolMessageType('Settings', (_message.Message,), dict(

  Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), dict(

    Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), dict(
      DESCRIPTOR = _SETTINGS_MAP_COORDINATE,
      __module__ = 'match_pb2'
      # @@protoc_insertion_point(class_scope:robotgame.Settings.Map.Coordinate)
      ))
    ,
    DESCRIPTOR = _SETTINGS_MAP,
    __module__ = 'match_pb2'
    # @@protoc_insertion_point(class_scope:robotgame.Settings.Map)
    ))
  ,
  DESCRIPTOR = _SETTINGS,
  __module__ = 'match_pb2'
  # @@protoc_insertion_point(class_scope:robotgame.Settings)
  ))
_sym_db.RegisterMessage(Settings)
_sym_db.RegisterMessage(Settings.Map)
_sym_db.RegisterMessage(Settings.Map.Coordinate)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(

  Bot = _reflection.GeneratedProtocolMessageType('Bot', (_message.Message,), dict(
    DESCRIPTOR = _STATE_BOT,
    __module__ = 'match_pb2'
    # @@protoc_insertion_point(class_scope:robotgame.State.Bot)
    ))
  ,
  DESCRIPTOR = _STATE,
  __module__ = 'match_pb2'
  # @@protoc_insertion_point(class_scope:robotgame.State)
  ))
_sym_db.RegisterMessage(State)
_sym_db.RegisterMessage(State.Bot)

Actions = _reflection.GeneratedProtocolMessageType('Actions', (_message.Message,), dict(

  Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
    DESCRIPTOR = _ACTIONS_ACTION,
    __module__ = 'match_pb2'
    # @@protoc_insertion_point(class_scope:robotgame.Actions.Action)
    ))
  ,
  DESCRIPTOR = _ACTIONS,
  __module__ = 'match_pb2'
  # @@protoc_insertion_point(class_scope:robotgame.Actions)
  ))
_sym_db.RegisterMessage(Actions)
_sym_db.RegisterMessage(Actions.Action)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
